/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddProductDialog: typeof import('./src/components/layouts/AddProductDialog.vue')['default']
    AdminLayout: typeof import('./src/components/layouts/AdminLayout.vue')['default']
    CartIcon: typeof import('./src/components/CartIcon.vue')['default']
    ClientLayout: typeof import('./src/components/layouts/ClientLayout.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DrinkMenu: typeof import('./src/components/layouts/DrinkMenu.vue')['default']
    FoodMenu: typeof import('./src/components/layouts/FoodMenu.vue')['default']
    HeaderMenu: typeof import('./src/components/HeaderMenu.vue')['default']
    HistoryRecord: typeof import('./src/components/layouts/HistoryRecord.vue')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
